### ISSUE TITLE
Launching new gamesandstuff windows app (seems) to trigger a security scan

### ISSUE THREAD

**Issue by Hoot679** [letsgoaway-games/gamesandstuff#7]
![cloud security scan](https://user-images.githubusercontent.com/70825884/205816101-0055cbe8-ad4e-40d6-b6d9-1a8ff7edf00f.png)

**Comment by letsgoaway-games** [comment]
hmm. i can promise you there is no virus because i just built it and put it into a zip.
its probably because it was downloaded from the internet and windwos defender wants to make sure its safe. shouldnt be an issue and it should still run fine

**Comment by Hoot679** [comment]
yeah
i know it wouldn't be a virus, otherwise windows would've prevented me from downloading it
